name = "PyVirtualenv"
uuid = "91719084-bad4-11e8-3336-8bad47a10c55"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[extras]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["PyCall", "Test"]
